/**
 * Orientation and model↔drawing agreement.
 *
 * The poster once drew the mirror image of its own model: `project()` returns
 * canvas-convention coordinates (down-positive, north-negative, pinned by
 * `astro.test.ts`'s "north-up" case), but `unitToCanvas` applied a
 * math-to-canvas flip to them. Every renderer agreed with every other renderer
 * — PNG, SVG and PDF all mirror identically — while the hit-test read the
 * unmirrored model, so hovering the canvas named the mirror image of the
 * cursor and the figure table (direct indices, no coordinates) stayed correct.
 *
 * Nothing caught it because every oracle was self-referential: the reference
 * PNGs are generated by the same renderer they guard, and the e2e zoom test
 * asserted a reset button rather than a position. These tests pin the
 * agreement directly, in both directions.
 */
import { describe, expect, it } from "bun:test";
import { project } from "../astro.ts";
import {
  AXIS_EXTENT,
  buildSkyModel,
  CANVAS_W,
  DISK_CX,
  DISK_CY,
  DISK_R,
  type SegmentRow,
  type StarRow,
} from "../skymodel.ts";
import type { SharePayload } from "../share.ts";
import { posterGeometry, unitToCanvas } from "./poster.ts";

function payload(): SharePayload {
  return {
    v: 1,
    lat: 40.758,
    lon: -73.9855,
    place: "Times Square",
    when_utc: "2026-01-01T00:00:00Z",
    tz: "UTC",
    options: {
      projection: "stereographic",
      fisheye_strength: 1.0,
      min_separation: 0,
      magnitude_limit: 5.8,
      glow: false,
      glow_intensity: 0,
      constellations: true,
      constellation_labels: true,
      shape: "circle",
      title: null,
    },
  };
}

describe("orientation", () => {
  it("draws north above the centre, as the model holds it", () => {
    // Due north, high up: the projection holds it at negative y (up in
    // canvas convention) and both representations must agree it is up.
    const p = project("stereographic", 40, 0, 1.0);
    expect(p.y).toBeLessThan(0);
    const modelPy = DISK_CY + p.y * DISK_R;
    expect(modelPy).toBeLessThan(DISK_CY);
    const [, drawnAy] = unitToCanvas(
      p.x,
      p.y,
      posterGeometry(CANVAS_W),
    );
    expect(drawnAy).toBeLessThan(DISK_CY);
  });

  it("the disc scale is one value, not two", () => {
    // The ring is drawn at `(1 / AXIS_EXTENT) * (sizePx / 2)`; the model must
    // use the same radius or the cursor and the drawing drift apart with
    // distance from the centre (9px at the rim under the old 368 literal,
    // against a 12px hit tolerance).
    expect(DISK_R).toBeCloseTo(CANVAS_W / 2 / AXIS_EXTENT, 9);
  });
});

describe("model pixels coincide with drawn pixels", () => {
  // Synthetic stars at spread unit positions, so the agreement is checked
  // across the disc rather than at one convenient point.
  const catalog: StarRow[] = [
    { hip: 1, raDeg: 0, decDeg: 60, mag: 2.0 },
    { hip: 2, raDeg: 90, decDeg: 20, mag: 2.5 },
    { hip: 3, raDeg: 180, decDeg: -20, mag: 3.0 },
    { hip: 4, raDeg: 270, decDeg: 45, mag: 3.5 },
  ];
  const segments: SegmentRow[] = [
    ["Tst", "Test", 1, 2],
    ["Tst", "Test", 3, 4],
  ];

  it("every star draws where the hit-test looks", () => {
    const model = buildSkyModel(payload(), catalog, segments);
    expect(model.stars.length).toBeGreaterThan(0);
    const geometry = posterGeometry(CANVAS_W);
    for (const star of model.stars) {
      const [ax, ay] = unitToCanvas(star.unitX, star.unitY, geometry);
      // Exact up to float rounding: same scale, same sign, by construction.
      // Anything coarser here re-opens the gap this file exists to close.
      expect(ax).toBeCloseTo(star.px, 9);
      expect(ay).toBeCloseTo(star.py, 9);
    }
  });

  it("figure centroids land on their own lines", () => {
    // Labels are placed by mapping the centroid back through the preview
    // geometry; at the unified scale that round-trips onto the centroid
    // pixels exactly, so a label cannot sit apart from its figure.
    const model = buildSkyModel(payload(), catalog, segments);
    const geometry = posterGeometry(CANVAS_W);
    for (const figure of model.figures) {
      const ux = (figure.centroidX - DISK_CX) / DISK_R;
      const uy = (figure.centroidY - DISK_CY) / DISK_R;
      const [lx, ly] = unitToCanvas(ux, uy, geometry);
      expect(lx).toBeCloseTo(figure.centroidX, 9);
      expect(ly).toBeCloseTo(figure.centroidY, 9);
    }
  });
});
