#!/usr/bin/env python3
"""Emit the poster face's glyph coverage as a tiny generated module.

The browser cannot read `assets/fonts/CormorantGaramond.ttf` — it is a
build-time asset, and `node:fs` does not exist there. Shipping a second copy
under `public/` would add 1.2 MB to the bucket and to every visitor's first
load, purely so the client could ask whether one character is drawable.

So the `cmap` is read here, at build time, and reduced to the smallest thing
that answers the question: a list of inclusive code-point ranges. That is a few
hundred bytes, ships in the JS bundle, and — the reason for doing it this way —
the browser and the unit suite read *the same generated constant*, so they
cannot disagree.

`site/src/lib/render/glyph-coverage.generated.ts` is checked in, and
`glyph-coverage.test.ts` regenerates and compares, so changing the font without
regenerating fails the suite rather than silently shipping stale coverage.

Run: uv run python scripts/generate_glyph_coverage.py [--check]
"""
from __future__ import annotations

import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT = ROOT.parent / "assets" / "fonts" / "CormorantGaramond.ttf"
OUTPUT = ROOT / "src" / "lib" / "render" / "glyph-coverage.generated.ts"


def u16(data: bytes, at: int) -> int:
    return struct.unpack_from(">H", data, at)[0]


def u32(data: bytes, at: int) -> int:
    return struct.unpack_from(">I", data, at)[0]


def find_table(data: bytes, tag: bytes) -> bytes:
    for index in range(u16(data, 4)):
        record = 12 + index * 16
        if data[record : record + 4] == tag:
            length = u32(data, record + 12)
            offset = u32(data, record + 8)
            return data[offset : offset + length]
    raise SystemExit(f"font has no {tag!r} table; is it a TrueType file?")


def coverage(data: bytes) -> set[int]:
    """Every code point the `cmap` maps to a glyph."""
    cmap = find_table(data, b"cmap")
    points: set[int] = set()

    def read_subtable(offset: int) -> set[int]:
        fmt = u16(cmap, offset)
        found: set[int] = set()
        if fmt == 4:
            seg_count = u16(cmap, offset + 6) // 2
            ends, starts = offset + 14, offset + 14 + seg_count * 2 + 2
            for segment in range(seg_count):
                end = u16(cmap, ends + segment * 2)
                start = u16(cmap, starts + segment * 2)
                if start > end:
                    continue
                found.update(range(start, min(end, 0xFFFF) + 1))
        elif fmt == 12:
            for group in range(u32(cmap, offset + 12)):
                at = offset + 16 + group * 12
                found.update(range(u32(cmap, at), u32(cmap, at + 4) + 1))
        return found

    for index in range(u16(cmap, 2)):
        record = 4 + index * 8
        platform, encoding = u16(cmap, record), u16(cmap, record + 2)
        offset = u32(cmap, record + 4)
        if platform == 10:  # Windows UCS-4: the only one spanning the astral planes
            points |= read_subtable(offset)
            return points
        if platform == 0 or (platform == 3 and encoding == 1) or platform == 0:
            points |= read_subtable(offset)
    if not points:
        raise SystemExit("cmap has no readable Unicode subtable")
    return points


def to_ranges(points: set[int]) -> list[tuple[int, int]]:
    ordered = sorted(points)
    ranges: list[tuple[int, int]] = []
    start = previous = ordered[0]
    for code in ordered[1:]:
        if code == previous + 1:
            previous = code
            continue
        ranges.append((start, previous))
        start = previous = code
    ranges.append((start, previous))
    return ranges


def render(ranges: list[tuple[int, int]], total: int) -> str:
    lines = ", ".join(f"[0x{lo:X}, 0x{hi:X}]" for lo, hi in ranges)
    return f"""/**
 * GENERATED by `scripts/generate_glyph_coverage.py` — do not edit.
 *
 * The inclusive code-point ranges the bundled poster face
 * (`assets/fonts/CormorantGaramond.ttf`) has a glyph for, read from its `cmap`
 * at build time. {total} code points in {len(ranges)} ranges.
 *
 * Generated rather than shipped so the browser does not have to download a
 * 1.2 MB font to answer whether one character is drawable, and so the unit
 * suite and the client read the same constant instead of two answers that could
 * drift. `glyph-coverage.test.ts` regenerates and compares, so changing the
 * font without regenerating fails the suite.
 */
export const POSTER_FONT_RANGES: readonly (readonly [number, number])[] = [
  {lines},
];

/** Does the poster face have a glyph for this code point? */
export function posterFontHasGlyph(codePoint: number): boolean {{
  let low = 0;
  let high = POSTER_FONT_RANGES.length - 1;
  while (low <= high) {{
    const mid = (low + high) >> 1;
    const [start, end] = POSTER_FONT_RANGES[mid] as [number, number];
    if (codePoint < start) high = mid - 1;
    else if (codePoint > end) low = mid + 1;
    else return true;
  }}
  return false;
}}
"""


def main() -> int:
    points = coverage(FONT.read_bytes())
    ranges = to_ranges(points)
    text = render(ranges, len(points))

    if "--check" in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != text:
            print(
                "FAIL: glyph-coverage.generated.ts is stale.\n"
                "Run: uv run python scripts/generate_glyph_coverage.py"
            )
            return 1
        print(f"ok: glyph coverage is current ({len(points)} code points)")
        return 0

    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}: {len(points)} code points in {len(ranges)} ranges")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
